# Generated by Django 3.0 on 2019-12-16 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField()),
                ('comments_artice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.Article')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
